In [2]:
import pandas as ps
import numpy as np
import seaborn as sb

from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
from sklearn.naive_bayes import CategoricalNB

datos = ps.read_csv('/content/sample_data/titanic_NB.csv', delimiter=';')
datos

      pclass  survived  sex   age  edad  sibsp  parch
0          3         1    1   5.0   1.0      0      0
1          3         0    2  11.0   1.0      0      0
2          2         1    1  12.0   1.0      0      0
3          3         1    1  13.0   2.0      0      0
4          2         0    2  14.0   2.0      0      0
...      ...       ...  ...   ...   ...    ...    ...
1304       3         0    2  40.0   3.0      1      1
1305       3         0    2  40.0   3.0      1      1
1306       3         0    1  43.0   3.0      1      1
1307       3         0    2   NaN   NaN      1      1
1308       3         0    1   NaN   NaN      1      1

[1309 rows x 7 columns]

In [ ]:
from sklearn.model_selection import train_test_split

datos2 = datos[['pclass','survived','sex','edad','sibsp','parch']]
datos2

      pclass  survived  sex  edad  sibsp  parch
0          3         1    1   1.0      0      0
1          3         0    2   1.0      0      0
2          2         1    1   1.0      0      0
3          3         1    1   2.0      0      0
4          2         0    2   2.0      0      0
...      ...       ...  ...   ...    ...    ...
1304       3         0    2   3.0      1      1
1305       3         0    2   3.0      1      1
1306       3         0    1   3.0      1      1
1307       3         0    2   NaN      1      1
1308       3         0    1   NaN      1      1

[1309 rows x 6 columns]

In [ ]:
datos2 = datos2.dropna()

In [ ]:
datos2

      pclass  survived  sex  edad  sibsp  parch
0          3         1    1   1.0      0      0
1          3         0    2   1.0      0      0
2          2         1    1   1.0      0      0
3          3         1    1   2.0      0      0
4          2         0    2   2.0      0      0
...      ...       ...  ...   ...    ...    ...
1302       3         0    2   3.0      1      1
1303       3         0    1   3.0      1      1
1304       3         0    2   3.0      1      1
1305       3         0    2   3.0      1      1
1306       3         0    1   3.0      1      1

[1046 rows x 6 columns]

# Nueva secciÃ³n

In [ ]:
X_train, X_test = train_test_split(datos2,test_size=0.3,random_state=42)

In [ ]:
X_test

      pclass  survived  sex  edad  sibsp  parch
1007       2         1    1   1.0      0      1
280        3         0    1   3.0      0      0
829        3         0    2   3.0      1      0
318        2         0    2   3.0      0      0
1260       3         0    2   1.0      1      1
...      ...       ...  ...   ...    ...    ...
815        3         0    1   3.0      1      0
420        1         1    1   3.0      0      0
1173       2         1    2   1.0      0      1
281        3         0    2   3.0      0      0
266        1         1    2   3.0      0      0

[314 rows x 6 columns]

In [ ]:
y_train = X_train['survived']
y_test = X_test['survived']
X_train =X_train[['pclass','sex','edad','sibsp','parch']]
X_train

      pclass  sex  edad  sibsp  parch
494        3    2   3.0      0      0
449        1    2   3.0      0      0
355        1    2   3.0      0      0
450        1    1   3.0      0      0
1181       2    2   1.0      0      1
...      ...  ...   ...    ...    ...
330        3    1   3.0      0      0
466        3    2   3.0      0      0
121        3    1   3.0      0      0
1305       3    2   3.0      1      1
1095       3    1   3.0      1      1

[732 rows x 5 columns]

In [ ]:
X_test =X_test[['pclass','sex','edad','sibsp','parch']]
X_test

      pclass  sex  edad  sibsp  parch
1007       2    1   1.0      0      1
280        3    1   3.0      0      0
829        3    2   3.0      1      0
318        2    2   3.0      0      0
1260       3    2   1.0      1      1
...      ...  ...   ...    ...    ...
815        3    1   3.0      1      0
420        1    1   3.0      0      0
1173       2    2   1.0      0      1
281        3    2   3.0      0      0
266        1    2   3.0      0      0

[314 rows x 5 columns]

In [ ]:
ct = CategoricalNB()
  # para datos continuos hay que usar
  # gauss = GaussianNB()

In [ ]:
ct.fit(X_train,y_train) #funcion para hacer ajuste de bayes

CategoricalNB()

In [ ]:
pronostico = ct.predict(X_test)

In [ ]:
pronostico

array([1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0])

In [ ]:
print (ct.score(X_test,y_test))

0.7961783439490446

In [ ]:
confusion_matrix(y_test,pronostico) #los de diagonal se suman para obtener la eficiencia del algoritmo (160+90) =250

#se suma todo (160+19+45+90) = 314 / 250 =0.79% = eficiencia

array([[160,  19],
       [ 45,  90]])